### ISSUE TITLE
TLS 1.3 mbedtls_ssl_get_psk_to_offer leaves data un-initialized

### ISSUE THREAD

**Issue by rlezuo1** [Mbed-TLS/mbedtls#6281]
What I try (and expect to work):
`./ssl_server2 server_port=2799 force_ciphersuite=TLS1-3-AES-128-GCM-SHA256 tls13_kex_modes=psk_ephemeral psk=fcc56e7668194a4775e5b36e2735551a  force_version=tls13`

and

`./ssl_client2 server_port=2799 force_ciphersuite=TLS1-3-AES-128-GCM-SHA256 tls13_kex_modes=psk_ephemeral psk=fcc56e7668194a4775e5b36e2735551a  force_version=tls13`

however, the client fails -0x7100 which I've pin-pointed to:
```
ssl_tls13_client.c:0492: |2| ECDH curve: x25519
ssl_tls13_client.c:1535: |3| found pre_shared_key extension
ssl_tls13_client.c:1313: |1| mbedtls_ssl_set_hs_psk() returned -28928 (-0x7100)
```
gdb reveals:
```
(gdb) bt
#0  mbedtls_ssl_set_hs_psk (ssl=0x7fffffff81d0, psk=0x555555674033 "", psk_len=140737488323024) at ssl_tls.c:1702
#1  0x00005555555986a9 in ssl_tls13_parse_server_pre_shared_key_ext (ssl=0x7fffffff81d0, buf=0x55555567405b "", end=0x55555567405d "") at ssl_tls13_client.c:1310
#2  0x0000555555598f87 in ssl_tls13_parse_server_hello (ssl=0x7fffffff81d0, 
    buf=0x555555674001 "\003\003\236\300=Pe\351\253\360\017\250\246\256\343+_\374\234\v\022\334\t4\201\030?\262x\226\365h\346\036", end=0x55555567405d "", is_hrr=0)
    at ssl_tls13_client.c:1542
#3  0x0000555555599424 in ssl_tls13_process_server_hello (ssl=0x7fffffff81d0) at ssl_tls13_client.c:1731
#4  0x000055555559b273 in mbedtls_ssl_tls13_handshake_client_step (ssl=0x7fffffff81d0) at ssl_tls13_client.c:2529
#5  0x000055555557f7ba in mbedtls_ssl_handshake_step (ssl=0x7fffffff81d0) at ssl_tls.c:3265
#6  0x000055555557f91a in mbedtls_ssl_handshake (ssl=0x7fffffff81d0) at ssl_tls.c:3334
#7  0x000055555556245c in main (argc=6, argv=0x7fffffffd938) at ssl/ssl_client2.c:2174
```

=> i.e. psk_len is totally off (and psk points to some random location)

The root cause seems to this call to initialize psk and psk_len (in library/ssl_tls13_client.c:1276)

```
    if( mbedtls_ssl_get_psk_to_offer( ssl, NULL, &psk, &psk_len,
                                      &psk_identity, &psk_identity_len ) != 0 )
```

in mbedtls_ssl_get_psk_to_offer ptrs_present will be 0 (psk_type passed as NULL pointer by the caller!)
And because ssl->conf->psk != NULL mbedtls_ssl_get_psk_to_offer returns success (0) but did not init the values!

**Comment by rlezuo1** [comment]
makes my test work:

```
diff --git a/library/ssl_tls13_client.c b/library/ssl_tls13_client.c
index 505f8dda8..13ffdceca 100644
--- a/library/ssl_tls13_client.c
+++ b/library/ssl_tls13_client.c
@@ -1273,7 +1273,9 @@ static int ssl_tls13_parse_server_pre_shared_key_ext( mbedtls_ssl_context *ssl,
      * NOTE: Ultimately, we want to offer multiple PSKs, and in this
      *       case, we need to iterate over them here.
      */
-    if( mbedtls_ssl_get_psk_to_offer( ssl, NULL, &psk, &psk_len,
+    int psk_type;
+
+    if( mbedtls_ssl_get_psk_to_offer( ssl, &psk_type, &psk, &psk_len,
                                       &psk_identity, &psk_identity_len ) != 0 )
     {
         /* If we haven't offered a PSK, the server must not send
```

**Comment by ronald-cron-arm** [comment]
We are currently adding support for PSK in TLS 1.3. This is work in progress. The change you propose is indeed needed and done in the PR finalizing the support for external PSKs on client side: #6194.
