### ISSUE TITLE
Make jsonschema optional when parsing driver

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#6596]
`generate_driver_wrappers.py` currently requires two Python packages: Jinja2 and jsonschema. Jinja2 is fundamentally necessary, but jsonschema is only used for validation and could be optional.

A lot of consumers of the development version of Mbed TLS don't have drivers, so they won't be feeding custom data to `generate_driver_wrappers.py` and it would be nice to remove this requirement. (It would be nice not to require jinja eiher, but that's unavoidable unless we completely rewrite the script.)

Note that we should have something on the CI that checks that the script works without `jsonschema`. Presumably by moving `jsonschema` out of `driver.requirements.txt` (or at least out of the inclusion chain of `basic.requirements.txt`) and setting up a venv with just the minimum.

**Comment by rob-the-dude** [comment]
+1 for this request.  It's actually quite beautiful that previous versions of mbedTLS have been able to build, out of the box, with nothing more than make and a compiler.  The added installation of system-level packages is very disappointing, particularly for many people who probably don't need anything very custom.

**Comment by gilles-peskine-arm** [comment]
You don't need these python packages (or python at all, in fact) just to build the library from a release. You need python to build the tests. You need python with the jinja2 and jsonschema packages to build the library with hardware drivers (for accelerators or secure elements), or if you're building the development branch.

**Comment by snej** [comment]
That’s not my experience. I’m trying to build from source and CMake fails very quickly:

```
$ mkdir build && cd build && cmake --build .
[  0%] Generating psa_crypto_driver_wrappers.c
[  0%] Generating suites/test_suite_ecp.generated.data
[  0%] Generating psa_constant_names_generated.c
[  0%] Generating suites/test_suite_psa_crypto_generate_key.generated.data, suites/test_suite_psa_crypto_low_hash.generated.data, suites/test_suite_psa_crypto_not_supported.generated.data, suites/test_suite_psa_crypto_op_fail.generated.data, suites/test_suite_psa_crypto_storage_format.current.data, suites/test_suite_psa_crypto_storage_format.v0.data
[  0%] Generating suites/test_suite_bignum.generated.data, suites/test_suite_bignum_core.generated.data, suites/test_suite_bignum_mod.generated.data, suites/test_suite_bignum_mod_raw.generated.data
[  0%] Generating query_config.c
[  0%] Built target mbedtls_test_helpers
[  0%] Built target generate_query_config_c
[  3%] Built target mbedtls_test
Traceback (most recent call last):
  File "/Users/snej/Projects/coro/vendor/mbedtls/library/../scripts/generate_driver_wrappers.py", line 29, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
```

**Comment by tom-cosgrove-arm** [comment]
> I’m trying to build from source

If you mean "I've checked out `development`" then yes, you need the python packages as Gilles says ("You need ... if you're building the development branch").

However, you don't need them if you build from a source release:

```
$ curl -OL https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v3.4.1.zip
$ unzip -q mbedtls-v3.4.1.zip
$ cd mbedtls-3.4.1
$ make CC=clang -j8
  CC    aes.c
  CC    aesni.c
  CC    aesce.c
  CC    aria.c
  CC    asn1parse.c
  CC    asn1write.c
  CC    base64.c
  CC    bignum.c
:
  CC    test_suite_aes.ofb.c
  CC    test_suite_cipher.null.c
$ echo $?
0
```

This was on a Docker image where I removed the python packages:

```
$ python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jinja2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'jinja2'
>>> import jsonschema
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'jsonschema'
>>>
```

**Comment by barracuda156** [comment]
Joining in, please make `jsonschema` optional. With Rust being forced now, it is a very undesirable dependency to have.

**Comment by kailun-qin** [comment]
> However, you don't need them if you build from a source release

@tom-cosgrove-arm: This is indeed (still) the case for the v3.6.0 source release. However, with the latest v3.6.1, it seems that a dependency on `jsonschema` is now required.

Specifically, using a clean Ubuntu 22.04 docker image, I obtained the following with v3.6.0:
```
$ curl -OL https://github.com/Mbed-TLS/mbedtls/releases/download/v3.6.0/mbedtls-3.6.0.tar.bz2
$ tar -xvjf mbedtls-3.6.0.tar.bz2
$ cd mbedtls-3.6.0
$ make -j
  CC    aes.c
  CC    aesni.c
:
make[1]: Leaving directory '/mbedtls-3.6.0/tests'
make[1]: Entering directory '/mbedtls-3.6.0'
make[1]: Leaving directory '/mbedtls-3.6.0'
$ echo $?
  0
```
while with v3.6.1, I got:
```
$ curl -OL https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-3.6.1/mbedtls-3.6.1.tar.bz2
$ tar -xvjf mbedtls-3.6.1.tar.bz2
$ cd mbedtls-3.6.1
$ make -j
  CC    aes.c
  CC    aesni.c
:
  Gen   psa_crypto_driver_wrappers.h psa_crypto_driver_wrappers_no_static.c
  CC    psa_crypto_aead.c
  CC    psa_crypto_cipher.c
  CC    src/test_memory.c
  CC    src/threading_helpers.c
  CC    psa_crypto_client.c
Traceback (most recent call last):
  File "/mbedtls-3.6.1/library/../scripts/generate_driver_wrappers.py", line 18, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
  Gen   psa_crypto_driver_wrappers.h psa_crypto_driver_wrappers_no_static.c
  CC    psa_crypto_ecp.c
make[1]: *** [Makefile:384: psa_crypto_driver_wrappers.h] Error 1
make[1]: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "/mbedtls-3.6.1/library/../scripts/generate_driver_wrappers.py", line 18, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
make[1]: *** [Makefile:384: psa_crypto_driver_wrappers_no_static.c] Error 1
make[1]: Leaving directory '/mbedtls-3.6.1/library'
make: *** [Makefile:32: lib] Error 2
make: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/mbedtls-3.6.1/tests'
```

May I know if there have been any changes? Thanks!

**Comment by wyattoday** [comment]
@gilles-peskine-arm 

> You don't need these python packages (or python at all, in fact) just to build the library from a release. You need python to build the tests. You need python with the jinja2 and jsonschema packages to build the library with hardware drivers (for accelerators or secure elements), or if you're building the development branch.

Unfortunately the latest LTS release of mbedTLS (3.6.4) *does* require python and additional modules to build the library (not the tests, just the vanilla library out-of-the-box so to speak).

Covered here: https://github.com/Mbed-TLS/mbedtls/issues/10332

There likely needs to be a simple CI job to build the library with just bare-bones `C`, `make` and the handful of other `binutils` that come with c / make (and explicitly exclude `python` / `python3`, etc.).

And also the CD job needs to include the `psa_crypto_driver_wrappers.h` and `psa_crypto_driver_wrappers_no_static.c` alongside the other pre-generated files already included (`error.c`, `version_features.c`, `ssl_debug_helpers_generated.c`)

**Comment by barracuda156** [comment]
@wyattoday Looks like that is a result of a bug, so hopefully we are safe for now.
