### ISSUE TITLE
scripts\make_generated-files.bat giving errors

### ISSUE THREAD

**Issue by rzeeshan565** [Mbed-TLS/mbedtls#7869]
### Summary
scripts\make_generated-files.bat giving errors.
![image](https://github.com/Mbed-TLS/mbedtls/assets/30415504/a442970d-64c4-4035-b2c6-74126e680ff6)

### System information

Mbed TLS version (number or commit id): "3.4.0"
Operating system and version: Windowa 10 64bit
Configuration (if not default, please attach `mbedtls_config.h`): [https://drive.google.com/file/d/18uzyJMUYOEmgCoDKJRhfyPtNTeB8BqMG/view?usp=sharing](url)
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 8_2019_q3_update\bin\arm-none-eabi-gcc.exe
Additional environment information: 
python 3.6.0

### Expected behavior

should generate all the configuration-independent files

### Actual behavior

_(scripts) C:\Users\XXXXXX\Downloads\mbedtls-development>scripts\make_generated_files.bat

(scripts) C:\Users\XXXXXX\Downloads\mbedtls-development>python scripts\generate_driver_wrappers.py   || exit /b 1 
Traceback (most recent call last):
  File "scripts\generate_driver_wrappers.py", line 215, in <module>
    sys.exit(main())
  File "scripts\generate_driver_wrappers.py", line 210, in main
    generate_driver_wrapper_file(template_directory, output_directory, merged_driver_json)
  File "scripts\generate_driver_wrappers.py", line 72, in generate_driver_wrapper_file
    result = render(driver_wrapper_template_filename, driver_jsoncontext)
  File "scripts\generate_driver_wrappers.py", line 58, in render
    template = environment.get_template(os.path.basename(template_path))
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python36\site-packages\jinja2\environment.py", line 997, in get_template  
    return self._load_template(name, globals)
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python36\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python36\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python36\site-packages\jinja2\environment.py", line 749, in compile       
    source = self._parse(source, name, filename)
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python36\site-packages\jinja2\environment.py", line 606, in _parse        
    return Parser(self, source, name, filename).parse()
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python36\site-packages\jinja2\parser.py", line 1038, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python36\site-packages\jinja2\parser.py", line 1021, in subparse
    rv = self.parse_statement()
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python36\site-packages\jinja2\parser.py", line 175, in parse_statement
    return f()  # type: ignore
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python36\site-packages\jinja2\parser.py", line 236, in parse_for
    lineno = self.stream.expect("name:for").lineno
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python36\site-packages\jinja2\lexer.py", line 405, in expect
    if not self.current.test(expr):
AttributeError: 'Token' object has no attribute 'test'_

### Steps to reproduce

from root (mbedtls_development) run _scripts\make_generated_files.bat_

**Comment by gilles-peskine-arm** [comment]
This looks like an incompatible change in Jinja. What version of the `jinja2` package do you have? (Versions of packages that `jinja2` depends on may also be relevant.)

You can see which version we use in our [requirements.txt file](https://github.com/Mbed-TLS/mbedtls/blob/development/scripts/driver.requirements.txt).
